replicaCount: 1

image:
  repository: registry.helix-dev.synadia.io/helix
  tag: "tag-rc"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

helix: {}
  # publicUrl: "http://helix.local"
  # adminUrl: "http://localhost:8081"
  # port: 8080
  # adminPort: 8081
  # adminPort: 
  # logLevel: "info"
  # encryptionKey: ""
  # encryptionKeysRotated: []
  # dataDirectory: "/data"
  # postgresUrl: ""
  # prometheusUrl: ""

metrics: {}
  # port: 7777

embeddedPostgres:
  enabled: true
  persistent: false 
  # port: 5432
  # logLevel: "info"
  # pvc: {
  #   storageClass: ""
  #   size: "1Gi"
  # }

embeddedPrometheus: {
  enabled: true,
  persistent: false 
  # port: 9090
  # logLevel: "info"
  # pvc: {
  #   storageClass: ""
  #   size: "1Gi"
  # }
}

natsSystems: []
  # - name: "nats"
  #   urls: "nats://nats.example.com"
  #   accountServerUrl: "nats://nats.example.com"
  #   systemAccountCredsSecretName: "nats-system-account-creds"
  #   operatorSigningKey: "nats-operator-signing-key"

alertPoller: {}
  # enabled: true
  # logLevel: "info"
  # intervalSeconds: 30
  # retentionDays: 7

encryptionRotator: {}
  # enabled: true
  # logLevel: "info"
  # intervalSeconds: 3600
  # rotationIntervalDays: 0

serviceObservationPoller: {}
  # enabled: true
  # logLevel: "info"
  # intervalSeconds: 30

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false 
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: helix.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
